### ISSUE TITLE
Error on import reactive-qr

### ISSUE THREAD

**Issue by adrienGzc** [tigranbs/reactive-qr#4]
I get this error when I import your ReactiveQR component :

Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.binarize (jsQR.js?ae76:389)
    at x (jsQR.js?ae76:332)
    at eval (qr_decode.worker.js?2c11:9)

Maybe you know why and how to solve it?   :man_shrugging:

**Comment by michaelcohen716** [comment]
getting this too

**Comment by adrienGzc** [comment]
Finally, I don't use the lib.
